---
title: "seamap_app"
author: "Jasmine Hsiao"
date: "2024-03-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(shiny)
library(shinydashboard)
library(leaflet)
library(dplyr)
library(readr)
```

```{r}
#install.packages("leaflet")
```

## Data
```{r}
seamap <- read_csv("data/obis_seamap_swot_65e0e9344b011_20240229_153235_site_locations_csv.csv")
```


## The App
```{r}
#register_stadiamaps("cf7e4fa6-eb1a-4afb-a4a8-6d5d47e2a05a", write = FALSE)
```

```{r}
ui <- dashboardPage(
  dashboardHeader(title = "Sea Turtle Biogeography", titleWidth = 400),
  dashboardSidebar(
    selectInput("country", "Select Country:", choices = unique(seamap$country), selected = "Australia")
  ),
  dashboardBody(
    leafletOutput("map", width = "100%", height = "600px")
  )
)

server <- function(input, output) {
  filtered_data <- reactive({
    filter(seamap, country == input$country)
  })

  output$map <- renderLeaflet({
    center_lat <- mean(filtered_data()$latitude)
    center_lon <- mean(filtered_data()$longitude)
    
    leaflet() %>%
      addTiles(urlTemplate = "https://tiles.stadiamaps.com/tiles/osm_bright/{z}/{x}/{y}{r}.png",
               attribution = '&copy; <a href="https://stadiamaps.com/">Stadia Maps</a> contributors') %>%
      setView(lng = center_lon, lat = center_lat, zoom = 4) %>%
      addMarkers(data = filtered_data(),
                 lng = ~longitude, lat = ~latitude,
                 popup = ~paste("Location: ", country))
  })
}

shinyApp(ui, server)
```


