---
title: "Sea map"
author: "Ketong Zhang"
date: "2024-03-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

load the packages
```{r}
library(tidyverse)
library(janitor)
library(dplyr)
library(naniar)
```

load the csv file
```{r}
seamap <- read_csv("data/obis_seamap_swot_65e0e9344b011_20240229_153235_site_locations_csv.csv") %>% clean_names()
```
overview the data
```{r}
glimpse(seamap)
```

countries that sea turtles located / appear the most
australia is the top 1
make sense because the oceans and beaches located in australia
```{r}
seamap %>% 
  filter(country != "NA") %>% 
  count(country) %>% 
  arrange(desc(n)) %>% 
  head(5) %>% 
  ggplot(aes(x = reorder(country,n), y=n))+
  geom_col(position = "dodge", fill = "lightgoldenrod")+
  coord_flip()+
  labs(title = "Top 5 countries",
       x = "Country",
       y = NULL)+
  theme(plot.title=element_text(size=rel(1.75), hjust = 0.5))
```
the nesting status
```{r}
seamap %>% 
  filter(nesting_status != "NA") %>% 
  count(nesting_status) %>% 
  ggplot(aes(x = nesting_status, y=n))+
  geom_col(fill = "darkolivegreen3")+
  labs(title = "Nesting status",
       x = NULL,
       y = NULL)+
  theme(plot.title=element_text(size=rel(1.75), hjust = 0.5))

```
the most commonly occur turtle species
```{r}
seamap %>%
  filter(!is.na(species)) %>%
  count(species, nesting_status) %>%
  ggplot(aes(x = nesting_status, y = n)) +
  geom_col(fill = "lightgreen") +
  facet_wrap(~ species, nrow = 3) +
  labs(title = "Nesting Status comparison by turtle species",
       x = "Nesting status",
       y = NULL)+
  theme(axis.text.x = element_text(angle = 50, hjust = 1)) +
  theme(plot.title=element_text(size=rel(1.75), hjust = 0.5))
```

most frequently appear species
```{r}
seamap %>% 
  filter(species!="NA") %>% 
  count(species) %>% 
  arrange(desc(n)) %>% 
  ggplot(aes(x = reorder(species, n), y=n, fill=species))+
  geom_col(fill = "lavender")+
  coord_flip()+
  theme_light()+
  labs(title = "Most frequently occur turtle species",
       x = "Species",
       y = NULL)+
  theme(plot.title=element_text(size=rel(1.75), hjust = 0.5))+
  scale_x_discrete()
```


